### ISSUE TITLE
The 2019 year isn't visible on wayback list of versions

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#900]
**What is the URL that originated the issue?**
https://preprod.arquivo.pt/wayback/20171213011046/http://www.citi.pt/

**What happened?**
The 2019 year isn't visible on left side on the wayback list of versions. The year is visible if the browser window is height enough, but it only has small height the year isn't visble. 

**What should have happened?**
All years should be visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/67018/79855138-74852b80-83c2-11ea-9dd6-d93de17746b4.png)
![image](https://user-images.githubusercontent.com/67018/79855199-8c5caf80-83c2-11ea-9176-589498ca4018.png)

**Comment by pcabritafccn** [comment]
This issue was already corrected.

**Comment by igobranco** [comment]
@pcabritafccn 
It still isn't working:

![image](https://user-images.githubusercontent.com/67018/79858347-32121d80-83c7-11ea-9f45-625f4508de7a.png)

**Comment by pcabritafccn** [comment]
This issue is not valid anymore as the team is working on a new wayback left menu (tale versions included) with a new html+ css structure on which will be applied the correct mouse behaviours.
